// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using C200_OfficialML.Model;

namespace C200_OfficialML.Model
{
    public class ConsumeModelAngela
    {
        private static Lazy<PredictionEngine<ModelInputAngela, ModelOutputAngela>> PredictionEngine = new Lazy<PredictionEngine<ModelInputAngela, ModelOutputAngela>>(CreatePredictionEngine);

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public static ModelOutputAngela Predict(ModelInputAngela input)
        {
            ModelOutputAngela result = PredictionEngine.Value.Predict(input);
            return result;
        }

        public static PredictionEngine<ModelInputAngela, ModelOutputAngela> CreatePredictionEngine()
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            string modelPath = @"..\C200_OfficialML.Model\MLModelAngela.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInputAngela, ModelOutputAngela>(mlModel);

            return predEngine;
        }
    }
}
