// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace C200_OfficialML.Model
{
    public class ModelInput
    {
        [ColumnName("Comments"), LoadColumn(0)]
        public string Comments { get; set; }


        [ColumnName("Label"), LoadColumn(1)]
        public string Label { get; set; }


    }
}
