// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace C200_ProjectML.Model
{
    public class ModelInputNicole
    {
        [ColumnName("ArticleId"), LoadColumn(0)]
        public float ArticleId { get; set; }


        [ColumnName("Text"), LoadColumn(1)]
        public string Text { get; set; }


        [ColumnName("Category"), LoadColumn(2)]
        public string Category { get; set; }


    }
}
