// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace C200_OfficialML.Model
{
    public class ModelInputAngela
    {
        [ColumnName("comment_text"), LoadColumn(0)]
        public string Comment_text { get; set; }


        [ColumnName("toxic"), LoadColumn(1)]
        public string Toxic { get; set; }


    }
}
